### ISSUE TITLE
Plugin does not show up in Protege

### ISSUE THREAD

**Issue by stefborg** [liveontologies/protege-black-box-justification-explanation#3]
Hello @matthewhorridge  @ykazakov @saarus72 ,

I have problems getting `protege-black-box-justification` to show up in Protege. All other explanation services, i.e., the original `explanations-workbench` and the new `protege-justification-explanation`, `protege-proof-justification`, `protege-proof-explanation` work fine.

When I select `Justifications` in the`Explanations` window, directly below it says `Using Proof Justifications as a computation service`. There is no option to switch to black-box justifications, and there is also no `Explanations` tab in the Protege preferences window. It seems that `protege-black-box-justification` is not correctly registered for the extension point (?), but there is no complaint about this in the log file.

I compiled all plugins (except `explanations-workbench`) from the current github master branches. I also tried it with clean Protege 5.0.0 and 5.2.0 installations. Removing `explanations-workbench` also makes no difference.

Do you have any idea what could be the problem?

Thanks,
Stefan

[protege.log](https://github.com/liveontologies/protege-black-box-justification/files/2359969/protege.log)

**Comment by ykazakov** [comment]
Did you try it with the latest Protege compiled from sources?
I think the extension point for Explanation preferences was added only after the 5.2.0 release, and maybe this is causing the problems.
https://github.com/protegeproject/protege/pull/653

**Comment by ykazakov** [comment]
Actually, you can just download the latest beta release:
https://github.com/protegeproject/protege-distribution/releases/

**Comment by stefborg** [comment]
Thanks, I will try that.

**Comment by stefborg** [comment]
I think I found the problem. The extension point was renamed at some point, but this was not reflected in the plugin.xml here. I opened a pull request with the fix.
